# default.properties
gauge_reports_dir = reports
overwrite_reports = true
screenshot_on_failure = true
logs_directory = logs
gauge_specs_dir = specs
csv_delimiter = ,
allow_multiline_step = false

allure_report_generate = true
allure_report_single_file = true
allure_report_language = zh
allure_report_theme = auto
allure_report_name = Gauge Allure Demo
allure_issue_pattern = https://jira.example.com/browse/%s
